name: Update README with blog entries

on:
  schedule:
   # Once a day at 8 AM
   - cron: 0 8 * * *

jobs:
  update:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://www.robincussol.com/rss.xml
          readme-section: blog-feed
          max: 10 # max number of items (default 5)
          template: "#### [{{ title }}]({{ link }}) \n*{{ contentSnippet }}*\n\n"
